### ISSUE TITLE
build: use `twine check --strict` instead of `python setup.py check -s -m`

### ISSUE THREAD

**Issue by vlcinsky** [pypyr/pypyr#227]
https://github.com/pypyr/pypyr/blob/master/ops/build.yaml#L22 expects twine to be used in future to test the metadata.

According to: https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup and my quick check this time is already here.

However, as `twine` is able to do the check only on built package, the question is, where to put it. I would think of moving i to packaging and forget about it in the lint.

**Comment by yaythomas** [comment]
Thanks for looking into this @vlcinsky, much appreciated! It was about time to check on where `twine` is at with the `check` progress, so thank you!

`setup.py check -m -s` does more than just validate the README. 

Compare https://hg.python.org/cpython/file/6969bac411fa/Lib/distutils/command/check.py to https://github.com/pypa/twine/blob/main/twine/commands/check.py

ln 82 in distutils `check.py` is of especial interest - the `check_metadata` function. There are required metadata checks for `name`, `version`, `url` and some checks on author/maintainer emails. These checks are in `setup.py check -m`, but I don't see them in `twine --check` (yet). Unless I'm missing it, in which case please feel free to correct me!

By the way, `twine check` is actually irrelevant for .md validation. . . so in the case of pypyr we've got a README.md rather than README.rst, it's not validating the README anyway. 

You raise a very valid point, though, which is when the check moves to twine we're going to have to re-think where to put it, and yes you're right, it'll prob have to go to the `package` step-group - it's actually there already, it's just not doing much under the covers in this case (since pypyr has an .md).

**Comment by yaythomas** [comment]
Superseded by new flit PEP 517 build front-end. #289
