### ISSUE TITLE
consider switching from obsolete bumpversion tool to bump2version

### ISSUE THREAD

**Issue by vlcinsky** [pypyr/pypyr#230]
Current pypyr CI/CD is using `bumpversion`, which declares being not maintained and recommends using it's own maintained fork [bump2version](https://github.com/c4urself/bump2version/).

**Comment by yaythomas** [comment]
ah yes, this is a bit of a (possibly on-going?) debacle. . .

Last time I looked at this, `bump2version` was planning to merge `bump2version` into the original `bumpversion`, so that `bumpversion` would become the new `bump2version`. 

In the meantime, doing `pip install bumpversion` actually installs the code from `bump2version` under the covers anyway. So we're not using unmaintained/stale code, it _is_ actually using `bump2version` already.

Confused yet? 😆 

So for this reason, I didn't go to `bump2version`, because the best information at the time was that if we changed to `bump2version` we would just have to change the dependency name back to `bumpversion` anyway soon as the switch was done. In the meantime, we're using the `bump2version` code anyway because that's what `bumpversion` installs .

The real question today is: whether it is still the case the name `bump2version` will deprecate on PyPy back to `bumpversion` - i.e whether `bumpversion` is still set to become/remain the "canonical" name. If so, we shouldn't take any action. If not, then we should probably change the name to `bump2version`.

Here is the full on-going discussion at `bump2version`: c4urself/bump2version#86

I must admit I am not entirely clear on exactly what the answer to the "what will the canonical name be" question is even now.

While we're here, I am also keeping an eye on moving pypyr to PEP517 builds & using `pyproject.toml` for config as soon as PyPa's `setuptools` achieve feature parity with the current `setup.py` + `setup.cfg` way of doing things. At this point, we should revisit entirely how to do versioning, because we might be able to do so in `pyproject.toml` itself - it looks like there are some plans for dynamically getting the version number from the code, which would be great.

**Comment by vlcinsky** [comment]
Thanks for the explanation. It sounds messy.

Regarding versioning - my best results come when using [pbr](https://docs.openstack.org/pbr/latest/)

setup.py is very short and constant:
```python
from setuptools import setup

setup(
    setup_requires=['pbr'],
    pbr=True,
)
```

All meta comes from `setup.cfg` (the example is for pbr package itself):
```
[metadata]
name = pbr
author = OpenStack Foundation
author-email = openstack-discuss@lists.openstack.org
summary = OpenStack's setup automation in a reusable form
description-file = README.rst
description-content-type = text/x-rst; charset=UTF-8
home-page = https://launchpad.net/pbr
project_urls =
    Bug Tracker = https://bugs.launchpad.net/pbr/
    Documentation = https://docs.openstack.org/pbr/
    Source Code = https://opendev.org/openstack/pbr
license = Apache-2
classifier =
    Development Status :: 4 - Beta
    Environment :: Console
    Environment :: OpenStack
    Intended Audience :: Developers
    Intended Audience :: Information Technology
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent
    Programming Language :: Python
keywords =
    setup
    distutils

[files]
packages =
    pbr
data_files =
    etc/pbr = etc/*
    etc/init =
        pbr.packaging.conf
        pbr.version.conf

[entry_points]
console_scripts =
    pbr = pbr.cmd:main
pbr.config.drivers =
    plain = pbr.cfg.driver:Plain
```
all requirements come from `requirements.txt` and `test_requirements.txt`

And what is best - versions are derived from git tags and commits after tags are getting their own versions calculated from distance from that commit. This works very well.

What I miss is clear dependency management as provided by `poetry`. poetry is currently having almost ready plugin system and there are two plugins [mtkennerly/poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) and [tiangolo/poetry-version-plugin](https://github.com/tiangolo/poetry-version-plugin) serving version management somehow - but this is very fresh thing and I have to decide how to use it practically for our own work (I am aware of one poetry issue breaking created packages using wheel format).

**Comment by yaythomas** [comment]
Thanks for mentioning `pbr`, I didn't even know about it! I'll check it out.

Yes, `poetry` is awesome - I've been keeping a close eye on it, it's truly some great work by @sdispater! `poetry`, and also `flit`, is all the more amazing & the devs are brave because they've taken on creating these new build tools while a lot of details from PEP517 & PEP518 were still in flux.

Same as you, while the Python world is still in a bit of a transitional phase with PEP517, I am just waiting to see where the dust is going to settle. . . 

There is also PyPa's new [build](https://setuptools.readthedocs.io/en/latest/build_meta.html) - which also looks like very promising and minimalist (the minimalism is very much to my liking).

But much as I enjoy experimenting, for pypyr I have to be responsible and  I don't want to create instability in the pypyr repo and harm end-users with broken builds or arbitrary changes during this transitional period. But I very much look forward to getting rid of that big old `setup.py` file when the time comes!

**Comment by vlcinsky** [comment]
@yaythomas as long as you manage to build functional python package, it does not matter what framework was used to build it up. 

I will complete rewrite of the sample project to pbr (using another [branch packby_pbr](https://github.com/pypyr/pypyr-to-invoke-comparison-example/tree/packby_pbr)) to show, how it works.

There is an issue for this https://github.com/pypyr/pypyr-to-invoke-comparison-example/issues/2
