### ISSUE TITLE
Run/skip evaluation ordering 

### ISSUE THREAD

**Issue by Reskov** [pypyr/pypyr#233]
Currently, pypyr always evaluates all of `run_me`, `skip_me`, `swallow_me` parameters. This is not an issue, but may produce some unexpected behavior, (or expected I am not pretty sure 😄  )

For example:

```yaml

steps:
   - name: pypyr.steps.echo
     run: False
     skip: !py "invalid"
     in:
       echoMe: "hello"
```

This example will fail with NameError
```
Something went wrong. Will now try to run on_failure.

NameError: name 'invalid' is not defined

```

But it should be clear without evaluation of skip_me that this step will never be executed. 

https://github.com/pypyr/pypyr/blob/67bc1795493c19e648e12f776a644f92e3bd2fc8/pypyr/dsl.py#L564

@yaythomas What do you think about lazy/strict evaluation of these params?

Something like:
```diff
         run_me = context.get_formatted_as_type(self.run_me, out_type=bool)
-        skip_me = context.get_formatted_as_type(self.skip_me, out_type=bool)
-        swallow_me = context.get_formatted_as_type(self.swallow_me,
-                                                   out_type=bool)
 
         if run_me:
+            skip_me = context.get_formatted_as_type(self.skip_me, out_type=bool)
+
             if not skip_me:
                 try:
                     if self.retry_decorator:
@@ -579,6 +578,9 @@ def run_conditional_decorators(self, context):
                     # else, not errors per se.
                     raise
                 except Exception as exc_info:
+                    swallow_me = context.get_formatted_as_type(self.swallow_me,
+                                                               out_type=bool)
+
                     if isinstance(exc_info, HandledError):

```

In addition, it will slightly optimize performance

**Comment by yaythomas** [comment]
great point, well made! 👍 

do you want to implement - it looks like you've made the changes already on your branch? Although it's a light enough change, right now I'm in the middle working through some experimental ideas regarding this #221 and it's consuming most of what little is left of my brain (p.s I'd be very interested to hear your feedback on whether #221 is sensible!).

> or expected I am not pretty sure 😄

haha, tbh, looking at the code, it'd be a bit pretentious of me to pretend I even thought about this "by design". . . I just unthinkingly put the 3 `get_formatted_as_type` at the top grouped together probably because it looked tidy, without thinking about it more 😆 

Just a note to be careful with the `swallow_me` evaluation. . .if formatting `swallow_me` fails, we should probably raise the formatting exception rather than the original pipeline exception, but we don't want to lose the original pipeline runtime error either, so `swallow_me = context.get_formatted_as_type(self.swallow_me, out_type=bool)` should prob go between ln 590-591. I'd rather that the `swallow_me` formatting error is a hard stop-everything error to force the pipeline author to rectify it, rather than silently swallow it or focusing on the step's runtime error instead.

**Comment by Reskov** [comment]
Wow! Thank you for such a great detailed reply. 

> do you want to implement?

yes, I will prepare PR soon.

**Comment by yaythomas** [comment]
much thanks 🙌 and as ever thank you for such a careful & precise bug/feature report! 🌟
